### ISSUE TITLE
Order of Welsh LAs is unintuitive

### ISSUE THREAD

**Issue by stupidpupil** [VictimOfMaths/COVID-19#1]
Something like the order shown [here](https://statswales.gov.wales/Catalogue/Community-Safety-and-Social-Inclusion/Welsh-Index-of-Multiple-Deprivation/WIMD-2019/localauthorityanalysis) is the usual one, as it preserves some geographic relationships (including health board boundaries). (Edit: Actually, that order isn't right either...)

Will sort out a pull request ASAP!

(Thank you for producing this, it's fantastic.)

**Comment by VictimOfMaths** [comment]
Hi Adam,

The order is deliberate - they are sorted by the date of the peak of confirmed cases, with the most recent at the top. That way you can immediately see where outbreaks are ongoing.

It would be very easy to reorder on a different variable (e.g. total cases or cases in the most recent day of data) by adjusting the arguments in the fct_reorder() call at the beginning of the code for the actual plot. Setting a different order manually (e.g. to make geographic sense) would just require you to manually set out the order of the factor levels.

Regards,

Colin

**Comment by stupidpupil** [comment]
Ah, apologies - of course! 

I think I was thrown by Denbighshire's possible second peak (which makes sense in the context of other northern LAs) and that (unsurprisingly) peak-order roughly matches the traditional sort-of-geographic ordering.
