### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by finestgreen** [VictimOfMaths/COVID-19#5]
Hi, could you consider including an open source licence to allow reuse and modification of your scripts?

**Comment by JonMinton** [comment]
I see this hasn't been touched for a while. But I'm curious about rationale.

For attribution, the readme.md file includes a link to this, as well as selected citation to use: https://figshare.shef.ac.uk/articles/dataset/CoVid_Plots_and_Analysis/12328226

The use of github forks means that the code can be reused and modified already (I can see 26 forks). What additional benefits would an open source licence offer?

**Comment by VictimOfMaths** [comment]
I agree, but to avoid any confusion I've clarified in the readme.md file that anyone is free to reuse any of this code for any purpose, except evil.
